### ISSUE TITLE
Add alarm acknowledgement

### ISSUE THREAD

**Issue by darrylmasson** [AG-Schumann/Doberman#46]
Or a way to tell Doberman that the issue is known and someone is on the way to deal with it.

**Comment by darrylmasson** [comment]
Recently came up with an idea for this: include with the email a link. This link will have the web monitor put two commands into the database: one to put the controller in question into the "testing" runmode, and one 30 minutes later to put it back into "default".

**Comment by ramirezdiego** [comment]
Sounds really good! We need a GeMSE web app...!

**Comment by adambrown1** [comment]
I'm going to resurrect this old discussion. I think this would be a very useful feature. I can think of two alternatives:
  * When alarm is "acknowledged", which I'm going to more generically call "supressed", no alarm gets logged any more, or
  * Alarms still get logged, but no alarm messages get sent any more

My preference is for the first, partly to avoid cluttering the alarm log (which can make it difficult to find a second type of alarm if there is one hidden in there). Related to this, at the moment there is a five minute "waiting period" between alarm notifications (email/SMS/...) being sent but in this time alarms are logged. Again this tends to lead to many repeated essentially identical alarms, and also means that if there is a second different alarm logged within that time no-one is notified. This latter is potentially a dangerous problem - imagine someone decides to fill the nitrogen, forgets to deactivate the alarm and then the nitrogen runs out while the dewar is gone, for example. I would therefore roll this into the alarm suppression, and do it on an alarm-by-alarm basis.

My proposal would be to store a "suppessed_until" date in the alarm node database entry. When an alarm is issued this is set to be five minutes from now, so that specific alarm but no others are turned off for five minutes. A user could also set a longer suppression time (via the website), of say 30 minutes.

**Comment by darrylmasson** [comment]
The idea I've been floating was that when we acknowledge an alarm (whatever that means), it puts the pipeline responsible for that alarm into silent mode for X minutes (30? To be discussed), which will prevent the creation of new alarms (alternative 1).

In general the whole subsystem responsible for collecting alarms and sending notifications is very old (dating back largely to the earliest commits), and I think the time is ripe to reimagine and redesign this feature, incorporating better ideas that deal with these known issues of repeated messages.

**Comment by darrylmasson** [comment]
The bigger idea was to have an endpoint for the website that allows for the silencing of alarms, and the link to do this added to the alarm email. If the existing auto-silence system is sufficient for the purposes of this feature then we can close this, otherwise there are still things for which a case can be made.

**Comment by adambrown1** [comment]
@jarongrigat Do we still want to do this? It is related to https://github.com/AG-Schumann/doberview2/issues/28
